### ISSUE TITLE
Remove the badge from the $GITHUB_STEP_SUMMARY 

### ISSUE THREAD

**Issue by rajbos** [green-coding-berlin/eco-ci-energy-estimation#10]
I don't think having the badge setup in each and every summary makes sense: it's something the user needs once and then never more. I'd suggest moving it to the README of this Action `https://<url>/<owner>/<repo>/etc` and / or moving it to the Actions output to still help users that want to get it.

![image](https://user-images.githubusercontent.com/6085745/230925461-6608cf3b-9eb1-4923-93c0-aa0bc5e47ae0.png)

**Comment by ArneTR** [comment]
The user needs the badge only once per workflow, that is true. But I think every other location to have this is unintuitive. Also the user has to piece together the URL then, because it is not generated automatically.

Since it is the last line also I think it does not really obfuscate any info or hinder readability.

**Comment by rajbos** [comment]
I use summaries a lot and this clutters that up with unneeded info (after adding the badge to the repo's README). Would it be an idea to add an input for this that defaults to `true`, but when `false` that badge info is not rendered at all?

**Comment by ArneTR** [comment]
If we make it as an optional functionality we could go even one step further and also allow disabling the graph and disabling the total metrics.
So effectively a step with three input variables that all default to true but can be turned off.

I see people also finding the graph maybe not too crazy helpful after a while or when inspecting an extremly long run.

I can see this feature making more sense now. Thanks for the input!

If you want to provide a PR with the possible flags for "get-measurement" and "display-results" we are happy to take it. Otherwise feel free to leave the issue and i will put a dev on it likely end of next week.

I see the options as follows:
- get-measurement
  + display-stats: True
  + send-data: True
- display-results
  + display-stats: True
  + display-graph: True
  + send-data: True
  + display-badge: True

**Comment by dan-mm** [comment]
@rajbos 

I have updated the action to take a few more optional flags:
- display-table
- display-graphs
- display-badge

Each of them are true by default, and meant to be used in the final `display-results' step and hides the corresponding output from being displayed in the github_step_summary. Hope this helps!
